language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.py3.txt --use-mirrors"
# command to run tests
script: python  -Wi -m unittest discover test