language: python
python:
  - "3.5"
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
  - sudo apt-get update
  - sudo apt-get install -qq python-simpleparse antiword poppler-utils tesseract-ocr tesseract-ocr-swe tesseract-ocr-osd tidy
services:
  - elasticsearch
install:
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install -r requirements.py2.txt; fi
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then LANG=en_US.UTF-8 pip install -r requirements.py3.txt; fi
  - pip install coveralls
script:
   - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then PYTHONWARNINGS=i coverage run --include "ferenda/*py" --omit "ferenda/thirdparty/*" -m unittest2 discover test; fi
   - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then PYTHONPATH=test PYTHONWARNINGS=i coverage run --include "ferenda/*py" --omit "ferenda/thirdparty/*" -m unites testPDFReader; fi
after_success:
  - coveralls
