build: false
version: 0.2.0.{build}
environment:
  matrix:
#    - PYTHON: "C:/Python27"
#      LXML: "lxml-3.3.5.win32-py2.7.exe"
    - PYTHON: "C:/Python34"
      LXML: "http://www.lfd.uci.edu/~gohlke/pythonlibs/an4m68cn/lxml-3.3.5.win32-py3.4.exe"
init:
  - "ECHO %PYTHON%"
  - "ECHO %LXML%"
  - ps: "ls C:/Python*"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:/ez_setup.py"
  - ps: Invoke-WebRequest $env:LXML -OutFile "C:/lxml.exe"
  - ps: "ls C:/"
install:
  - "%PYTHON%/python.exe c:/ez_setup.py"
  - "%PYTHON%/Scripts/easy_install.exe C:/lxml.exe"
test_script:
  - "%PYTHON%/python.exe setup.py test"