build: false
version: 0.2.1.dev9.{build}
environment:
  matrix:
    - PYTHON: "C:/Python27"
      LXML: "tools/win32/lxml-3.3.5.win32-py2.7.exe"
      REQUIREMENTS: "requirements.py2.txt"
    - PYTHON: "C:/Python34"
      LXML: "tools/win32/lxml-3.3.5.win32-py3.4.exe"
      REQUIREMENTS: "requirements.py3.txt"
init:
  - "ECHO %PYTHON%"
  - "ECHO %LXML%"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:/ez_setup.py"
  - ps: Invoke-WebRequest "https://raw.github.com/pypa/pip/master/contrib/get-pip.py" -OutFile "c:/get-pip.py"
  - ps: "git config --global core.autocrlf false" # always use unix lineendings
install:
  - "%PYTHON%/python.exe c:/ez_setup.py > NUL"
  - "%PYTHON%/python.exe c:/get-pip.py"
  - "%PYTHON%/Scripts/easy_install.exe %LXML%"
  - "%PYTHON%/Scripts/pip.exe -q install -r %REQUIREMENTS%"
test_script:
  - "%PYTHON%/python.exe -Wi tools/rununittest.py discover test"
